apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    app: service2
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: service2
  ports:
    - port: {{ .Values.service2.service.port }}
      targetPort: 8001

