apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app: service1
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - port: {{ .Values.service1.service.port }}
      targetPort: 8000

